global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels:
    datacenter: global

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
    scheme: http
    timeout: 10s

scrape_configs:

- job_name: Prometheus
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - 127.0.0.1:9090

- job_name: 'datacenter_federation'
  scrape_interval: 15s
  metrics_path: '/federate'

  honor_labels: true

  params:
    'match[]':
      - '{job="rancher-discovery"}'

  static_configs:
    - targets:
      - 'nhsuk-dev.uksouth.cloudapp.azure.com:9090'
      - 'nhsuk-staging.uksouth.cloudapp.azure.com:9090'
      - 'nhsuk-production.uksouth.cloudapp.azure.com:9090'
      - 'nhsuk-production-ukw.ukwest.cloudapp.azure.com:9090'
      - 'phe-staging.trafficmanager.net:9090'
      - 'phe-prod.trafficmanager.net:9090'

- job_name: 'HostMetrics'

  static_configs:
    - targets:
      - 'nhsuk-production-ukw01.ukwest.cloudapp.azure.com:19100'
      - 'nhsuk-production-ukw02.ukwest.cloudapp.azure.com:19100'
      - 'nhsuk-production-ukw03.ukwest.cloudapp.azure.com:19100'
      - 'nhsuk-production-ukw04.ukwest.cloudapp.azure.com:19100'
      - 'nhsuk-production-uks01.uksouth.cloudapp.azure.com:19100'
      - 'nhsuk-production-uks02.uksouth.cloudapp.azure.com:19100'
      - 'nhsuk-production-uks03.uksouth.cloudapp.azure.com:19100'
      - 'nhsuk-production-uks04.uksouth.cloudapp.azure.com:19100'
      labels:
        environment: production


- job_name: 'RancherServerMetrics'

  static_configs:
    - targets:
      - 'nhsuk-production-ukw01.ukwest.cloudapp.azure.com:18080'
      - 'nhsuk-production-ukw02.ukwest.cloudapp.azure.com:18080'
      - 'nhsuk-production-ukw03.ukwest.cloudapp.azure.com:18080'
      - 'nhsuk-production-ukw04.ukwest.cloudapp.azure.com:18080'
      - 'nhsuk-production-uks01.uksouth.cloudapp.azure.com:18080'
      - 'nhsuk-production-uks02.uksouth.cloudapp.azure.com:18080'
      - 'nhsuk-production-uks03.uksouth.cloudapp.azure.com:18080'
      - 'nhsuk-production-uks04.uksouth.cloudapp.azure.com:18080'
      labels:
        environment: production

- job_name: blackbox
  params:
    module:
    - http_2xx
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /probe
  scheme: http
  static_configs:
  - targets:
    - https://beta.nhs.uk/
    - https://beta.nhs.uk/finders/find-help/
    - https://beta.nhs.uk/book-a-gp-appointment/results?search=&postcode=ls28
    - https://beta.nhs.uk/gp-surgeries/39116
    - https://register-with-a-gp-beta.service.nhs.uk/
    - https://git.nhschoices.net
    - https://splunk.nhschoices.net
    - https://tc.nhschoices.net
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.*)
    target_label: __param_target
    replacement: $1
    action: replace
  - source_labels: [__param_target]
    separator: ;
    regex: (.*)
    target_label: instance
    replacement: $1
    action: replace
  - source_labels: []
    separator: ;
    regex: (.*)
    target_label: __address__
    replacement: blackbox-exporter:9115
    action: replace
