version: '2'

services:

  prometheus:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 5000
      port: 9090
      unhealthy_threshold: 3
      interval: 5000
      strategy: recreate

  prom-conf:
    scale: 1
    start_on_create: true

  grafana:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 5000
      port: 3000
      unhealthy_threshold: 3
      interval: 5000
      strategy: recreate

  grafana-storage:
    scale: 1
    start_on_create: true

  blackbox-exporter:
    scale: 1
    start_on_create: true

  alertmanager:
    scale: 1
    start_on_create: true
